listeners:
  - query_port: 10000
    motd: "&bEaglercraft 1.12 Gateway"
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    forced_hosts: {}
    ping_passthrough: false
    priorities:
      - shockbyte
    bind_local_address: true
    host: 0.0.0.0:10000
    max_players: 60
    tab_size: 60
    force_default_server: true

remote_ping_timeout: 5000
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: []
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload

log_pings: false
connection_throttle_limit: 0
server_connect_timeout: 10000
timeout: 30000
player_limit: -1
ip_forward: false
prevent_proxy_connections: false
online_mode: false
forge_support: false
disabled_commands: []

servers:
  shockbyte:
    motd: "&aShockbyte Minecraft Server"
    address: 157.85.94.60:20929
    restricted: false
